=== pranavjha/teapot/src/teapot/common/config/compiler.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- A configuration element consists of optional scripts, templates and styles elements-->
<!ELEMENT compile:configuration (scripts*,templates*,styles*)+>
<!--compilation-level is used to identify the compression level and the compilation strictness.
 This is overridden by the compilation option available in child elements. However, for resources 
 that are not mapped, The default compilation level specified here is used-->
<!ATTLIST compile:configuration 
	compilation-level (WHITESPACE_ONLY|SIMPLE_OPTIMIZATIONS|ADVANCED_OPTIMIZATIONS) #IMPLIED
>
<!--A script element is the container for all scripts that have to be compiled-->
<!ELEMENT scripts (to-file+)>
<!--basedir is the classpath relative path to the directory where the input files reside.
mergedir is the classpath relative path to the directory where the merged fles should be kept
compilation-level is used to identify the compression level and the compilation strictness.
 This is overridden by the compilation option available in child elements.-->
<!ATTLIST scripts 
	basedir CDATA #REQUIRED
	mergedir CDATA #REQUIRED
	compilation-level (WHITESPACE_ONLY|SIMPLE_OPTIMIZATIONS|ADVANCED_OPTIMIZATIONS) #IMPLIED
>
<!--A template element is the container for all templates that have to be compiled-->
<!ELEMENT templates (to-file+)>
<!--basedir is the classpath relative path to the directory where the input files reside.
mergedir is the classpath relative path to the directory where the merged fles should be kept
compilation-level is used to identify the compression level and the compilation strictness.
 This is overridden by the compilation option available in child elements.-->
<!ATTLIST templates 
	basedir CDATA #REQUIRED
	mergedir CDATA #REQUIRED
	compilation-level (WHITESPACE_ONLY|SIMPLE_OPTIMIZATIONS|ADVANCED_OPTIMIZATIONS) #IMPLIED
>
<!--A styles element is the container for all styles that have to be compiled-->
<!ELEMENT styles (to-file+)>
<!--basedir is the classpath relative path to the directory where the input files reside.
mergedir is the classpath relative path to the directory where the merged fles should be kept
compilation-level is used to identify the compression level and the compilation strictness.
 This is overridden by the compilation option available in child elements.-->
<!ATTLIST styles 
	basedir CDATA #REQUIRED
	mergedir CDATA #REQUIRED
	compilation-level (WHITESPACE_ONLY|SIMPLE_OPTIMIZATIONS|ADVANCED_OPTIMIZATIONS) #IMPLIED
>
<!-- A to-file element represents one atomic compilation. -->
<!ELEMENT to-file (name,(include+,exclude*)+)>
<!-- comma separated list of dependencies (file paths relative to basedir) which have to be compiled before compiling this file -->
<!ATTLIST to-file 
	dependency CDATA #IMPLIED
>
<!-- name of the compiled output file -->
<!ELEMENT name (#PCDATA)>
<!-- glob file patterns to exclude relative to basedir -->
<!ELEMENT include (#PCDATA)>
<!-- glob file patterns to include relative to basedir -->
<!ELEMENT exclude (#PCDATA)>
<!-- the protocol that is to be used to handle the file, if not specified, the default value will be file protocol -->
<!ATTLIST include 
	protocol (FILE|HTTP|SERVER) "FILE"
>
<!-- the protocol that is to be used to handle the file, if not specified, the default value will be file protocol -->
<!ATTLIST exclude 
	protocol (FILE|HTTP|SERVER) "FILE"
>

=== pranavjha/teapot/src/teapot/common/config/compiler.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE compile:configuration SYSTEM "compiler.dtd">
<compile:configuration>
	<!-- all static scripts are merged here -->
	<scripts mergedir="script" basedir="script">
		<to-file>
			<name>statics-all.js</name>
			<!-- load all statics except bootstrap(because its bootstrap!) and configurator 
				(configurator should be the last script to load) -->
			<include>statics/**.js</include>
			<exclude>statics/configurator.js</exclude>
			<exclude>statics/bootstrap.js</exclude>
			<!-- FIXME: move to a separate package -->
			<include>teapot/util/StaticUtils.js</include>
			<include>teapot/util/Logger.js</include>
			<!-- load the base classes -->
			<include>teapot/base/**.js</include>
			<!-- load utils classes -->
			<include>teapot/util/**.js</include>
			<!-- finally, load the configurator -->
			<include>statics/configurator.js</include>
		</to-file>
	</scripts>
	<!-- all dwr public scripts are merged here -->
	<scripts mergedir="script" basedir="dwr" compilation-level="SIMPLE_OPTIMIZATIONS">
		<to-file>
			<name>dwr-public.js</name>
			<include protocol="SERVER">engine.js</include>
			<include protocol="SERVER">interface/ScriptLogger.js</include>
		</to-file>
	</scripts>
	<!-- merging statics styles -->
	<styles mergedir="styles" basedir="styles">
		<to-file>
			<name>statics-all.css</name>
			<include>statics/**.gss</include>
			<include>teapot/ui/**.gss</include>
			<include>teapot/util/**.gss</include>
		</to-file>
	</styles>
	<!-- merging statics templates -->
	<templates mergedir="templates" basedir="templates">
		<to-file>
			<name>statics-all.js</name>
			<include>teapot/ui/**.soy</include>
			<include>teapot/util/**.soy</include>
		</to-file>
	</templates>
</compile:configuration>
